// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
// USER PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const CREATE_UPDATE_PROFILE = 'CREATE_UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_GITHUB_LANG = 'GET_GITHUB_LANG';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
// FLASHCARDS
export const GET_FLASHCARDS_CATEGORIES = 'GET_FLASHCARDS_CATEGORIES';
export const CREATE_FLASHCARDS_CATEGORY = 'CREATE_FLASHCARDS_CATEGORY';
export const GET_ALL_USER_FLASHCARDS = 'GET_ALL_USER_FLASHCARDS';
export const FLASHCARDS_ERROR = 'FLASHCARDS_ERROR';
export const SET_CURRENT_FLASHCARDS_CATEGORY =
  'SET_CURRENT_FLASHCARDS_CATEGORY';
export const SET_FLASHCARDS_CATEGORIES_LIST = 'SET_FLASHCARDS_CATEGORIES_LIST';
export const CREATE_NEW_FLASHCARD = 'CREATE_NEW_FLASHCARD';
export const SET_CURRENT_EDITED_FLASHCARD = 'SET_CURRENT_EDITED_FLASHCARD';
export const UPDATE_CURRENT_FLASHCARD = 'UPDATE_CURRENT_FLASHCARD';
export const DELETE_CURRENT_FLASHCARD = 'DELETE_CURRENT_FLASHCARD';
export const DELETE_FLASHCARDS_CATEGORY = 'DELETE_FLASHCARDS_CATEGORY';
// JOBS
export const GET_ALL_USER_COMPANIES = 'GET_ALL_USER_COMPANIES';
export const GET_ALL_USER_JOBS = 'GET_ALL_USER_JOBS';
export const CREATE_NEW_USER_JOB = 'CREATE_NEW_USER_JOB';
export const UPDATE_USER_JOB = 'UPDATE_USER_JOB';
export const DELETE_USER_JOB = 'DELETE_USER_JOB';
export const JOBS_ERROR = 'JOBS_ERROR';
export const FILTER_JOBS = 'FILTER_JOBS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_CURRENT_EDITED_JOB = 'SET_CURRENT_EDITED_JOB';
// COMPANIES
export const CREATE_NEW_USER_COMPANY = 'CREATE_NEW_USER_COMPANY';
export const UPDATE_USER_COMPANY = 'UPDATE_USER_COMPANY';
export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const DELETE_USER_COMPANY = 'DELETE_USER_COMPANY';
// LEARN
export const GET_ALL_USER_LEARN_CATEGORIES = 'GET_ALL_USER_LEARN_CATEGORIES';
export const GET_ALL_USER_LEARN_ITEMS = 'GET_ALL_USER_LEARN_ITEMS';
export const SET_CURRENT_LEARN_CATEGORY = 'SET_CURRENT_LEARN_CATEGORY';
export const SET_CURRENT_EDITED_LEARN_CATEGORY =
  'SET_CURRENT_EDITED_LEARN_CATEGORY';
export const DELETE_LEARN_CATEGORY = 'DELETE_LEARN_CATEGORY';
export const UPDATE_LEARN_CATEGORY = 'UPDATE_LEARN_CATEGORY';
export const CREATE_NEW_LEARN_CATEGORY = 'CREATE_NEW_LEARN_CATEGORY';
export const CREATE_NEW_LEARN_ITEM = 'CREATE_NEW_LEARN_ITEM';
export const UPDATE_LEARN_ITEM = 'UPDATE_LEARN_ITEM';
export const DELETE_LEARN_ITEM = 'DELETE_LEARN_ITEM';
export const LEARN_ERROR = 'LEARN_ERROR';
// OTHER
export const SET_LOADING = 'SET_LOADING';
export const SET_LEARN_ITEM_LOADING = 'SET_LEARN_ITEM_LOADING';
export const SET_LEARN_CATEGORY_LOADING = 'SET_LEARN_CATEGORY_LOADING';
